server:
  port: 8080


logging:
  level:
    root: INFO
    com.nba.realtime: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} [%thread] %clr(%-5level){faint,blue,green,yellow,red,magenta} %logger{36} - %msg%n"

# Security Setting -----------------------------------------------------------------------------------
security:
  ignore-security-check-uri-list:
    /swagger-ui/**,
    /v3/api-docs/**,
    /games/**,
    /players/**

rapidapi:
  url: https://api-nba-v1.p.rapidapi.com/
  host: api-nba-v1.p.rapidapi.com
  key: ${RAPIDAPI_KEY}
